---
title: "Praca domowa 4"
author: "Michał Cebula"
date: "`r Sys.Date()`"
output: 
  html_document:
    code_folding: "hide"
knit: (function(input, ...) {
    rmarkdown::render(input,output_dir = "..")
  })
---

<style type="text/css">
  .main-container {
    max-width: 1920px;
    margin: auto;
  }
  
  body {
    font-family: Helvetica;
    font-size: 14pt;
  }
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries, include=FALSE, message=FALSE}
library(dplyr)
library(ggplot2)
library(readr)
library(sf)
library(stringr)
```

```{r process_data, results='hide', message=FALSE}
fix_names <- function(string) {
  string |> 
    stringi::stri_trans_general("Latin-ASCII") |> 
    str_replace_all("[[:punct:]]", " ") |> 
    str_squish() |> 
    str_replace_all(" ", "_") |> 
    str_to_lower()
}
wyniki_glosowania <- read_csv2(
  "../Data/wyniki_gl_na_listy_po_powiatach_sejm.csv",
  name_repair = fix_names,
  col_types = list(
    kod_teryt = col_factor(),
    powiat = col_factor(),
    wojewodztwo = col_factor(),
    .default = col_integer()
  )
) |> 
  filter(!(powiat %in% c("statki", "zagranica"))) |> 
  mutate(kod_teryt = str_sub(kod_teryt, 1, 4))

granice_powiatow <- st_read("../Data/Powiaty.shp")
granice_wojewodztw <- st_read("../Data/Województwa.shp")

granice_wyniki <- granice_powiatow |> 
  inner_join(wyniki_glosowania, by = join_by(JPT_KOD_JE == kod_teryt))
```

```{r map, fig.dim=c(16, 9), fig.align='center', out.width='100%'}
custom_theme <- theme(
  axis.text = element_blank(),
  axis.line = element_blank(),
  axis.ticks = element_blank(),
  panel.border = element_blank(),
  panel.grid = element_blank(),
  axis.title = element_blank(),
  plot.title = element_text(size = 16, face = "bold",  hjust = 0.5),
  plot.caption = element_text(size = 12, hjust = 0.5),
  legend.title = element_text(size = 12, face = "bold", color = "black"),
  legend.text = element_text(size = 10, color = "black"),
  legend.key.size = unit(1, "cm")
)

ggplot() + 
  geom_sf(
    data = granice_wyniki, 
    aes(fill = w_tym_z_powodu_niepostawienia_znaku_x_obok_nazwiska_zadnego_kandydata 
               / liczba_kart_waznych)
  ) +
  geom_sf(
    data = granice_wojewodztw, 
    alpha = 0, 
    color = "black",
    linewidth = 0.5
  ) +
  scale_fill_viridis_c(
    labels = scales::percent_format(scale = 100)
  ) +
  labs(
    title = str_wrap(
      "Udział głosów unieważnionych z powodu niepostawienia znaku 'X' obok nazwiska żadnego kandydata, w wyborach parlamentarnych w Polsce w 2019. roku", 
      80
    ),
    fill = "Procent głosów",
    caption = str_wrap(
      "Mapa administracyjna Polski przedstawiająca udział procentowy głosów unieważnionych z powodu niepostawienia znaku 'X' obok nazwiska żadnego kandydata w stosunku do wszystkich ważnych kart, w wyborach parlamentarnych w Polsce w 2019. roku,  według poszczególnych powiatów.",
      120
    )
  ) +
  theme_bw() +
  custom_theme
```
