# -*- coding: utf-8 -*-
"""Kopia notatnika PD6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PD32efbpFwOICUwyRGBf0b_wt31u1dTq

# Praca domowa 6
"""



"""## Zadanie 1

"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


df = pd.read_csv("https://raw.githubusercontent.com/MI2-Education/2023L-ExploratoryDataAnalysis/main/homeworks/hw6/house_data.csv")

"""1. Jaka jest średnia cena nieruchomości położonych nad wodą, których jakoś wykończenia jest równa lub większa od mediany jakości wykończenia?

"""

med_jakosci= df['grade'].median()
domy = df[(df['waterfront'] == 1) & (df['grade'] >= med_jakosci)]

srednia_cena = domy['price'].mean()
srednia_cena

"""Odp: Średnia cena to ok. 1 784 151.7

2. Czy nieruchomości o 2 piętrach mają większą (w oparciu o wartości mediany) liczbę łazienek niż nieruchomości o 3 piętrach?
"""

two_floors = df[df['floors'] == 2]
three_floors = df[df['floors'] == 3]

med_baths_two = two_floors['bathrooms'].median()
med_baths_three = three_floors['bathrooms'].median()

med_baths_two > med_baths_three

"""Odp:Nie

3. Jak wygląda wartość kwartyla 0.25 oraz 0.75 jakości wykończenia nieruchomości położonych na północy biorąc pod uwagę czy ma ona widok na wodę czy nie ma?
"""

middle_point = (df['lat'].max() + df['lat'].min())/2
north = df[df['lat'] > middle_point]

view = north[north['waterfront'] == 1]
no_view = north[north['waterfront'] == 0]

# 0.25:

# Z widokiem :
print(np.percentile(view['grade'], 25))

# Bez widoku 
print(np.percentile(no_view['grade'], 25))

#  0.75:

# Z widokiem 
print(np.percentile(view['grade'], 75))

# Bez widoku 
print(np.percentile(no_view['grade'], 75))

"""Odp:
##Kwartyl 0.25:
z widokiem: 8.0;
bez widoku: 7.0
##Kwartyl 0.75:
z widokiem: 10.0;
bez widoku: 8.0

4. Pod którym kodem pocztowy jest położonych najwięcej nieruchomości i jaki jest rozstęp miedzykwartylowy dla ceny nieruchomości położonych pod tym adresem?
"""

code_count = df['zipcode'].value_counts()
majority = code_count.idxmax()
houses_majority = df[df['zipcode'] == majority]
iqr = np.percentile(houses_majority['price'], 75) - np.percentile(houses_majority['price'], 25)
iqr

"""Odp:262875.0

5. Ile percent nieruchomości ma wyższą średnią powierzchnię 15 najbliższych sąsiadów względem swojej powierzchni?
"""

with_bigger_neighbour = df[df['sqft_lot15'] > df['sqft_lot']]
n_b = with_bigger_neighbour.shape[0]
n = df.shape[0]

percent = 100*(n_b/n)
percent

"""Odp:Ok.39.5%

6. O ile percent więcej jest nieruchomości leżcych na północy zachód niż  nieruchomości leżących na południowy wschód?
"""

middle_point_lat = (df['lat'].max() + df['lat'].min())/2
middle_point_long = (df['long'].max() + df['long'].min())/2

north_west = df[(df['lat'] > punkt_srodkowy_lat) & (df['long'] < middle_point_long)]
south_east = df[(df['lat'] < punkt_srodkowy_lat) & (df['long'] > middle_point_long)]

liczba_north_west = north_west.shape[0]
liczba_south_east = south_east.shape[0]

percent = 100*(liczba_north_west - liczba_south_east)/(liczba_south_east)
percent

"""Odp:Około 18342.5%

# Zadanie 2

Dla wybranej zmiennej ze zbioru danych z Zadania 1 narysuj:

a) rozkład zmiennej jakościowej

b) rozkład zmiennej ilościowej

c) rozkład dwóch zmiennych (dowolna kombinacja jakościowej i ilościowej)

a)
"""

df.head
with_view= df['waterfront'].value_counts()
with_view
plt.bar(with_view.index, with_view.values)
plt.xlabel('Widok na morze: 0 - NIE, 1 - TAK')
plt.ylabel('Liczba mieszkań')
plt.title('Ile mieszkań ma widok na morze?')
plt.xticks([0,1])
plt.show()

"""b)"""

df.head
sns.violinplot(data = df, y = 'sqft_living')
plt.ylabel('powierzchnia w stopach kwadratowych')
plt.title('Rozkład powierzchni mieszkalnej')
plt.show()

"""c)"""

df.head
# liczba domów z daną liczbą pięter w podziale na z widokiem i bez widoku